<?php

$this->setup(array(
    'title' => 'Delete booking',
    'panel' => 'centered-panel large-sized',
    'tabs' => $this->backendDefaultTabs(),
    'back' => array(
        'Bookings' => $this->url('backend/booking'),
    ),
));

$bid = $this->booking->need('bid');

?>

<div>
    <h1><?= $this->t('Delete booking') ?></h1>

    <div class="separator separator-line"></div>

    <div class="padded centered-text">
        <div><span class="symbolic symbolic-warning"><?= $this->t('Deleting this booking cannot be undone. Are you sure?') ?></span></div>

        <div class="separator-small"></div>

        <div class="centered-text">
            <a href="<?= $this->url('backend/booking') ?>" class="default-button"><?= $this->t('No, cancel') ?></a>
            <a href="<?= $this->url('backend/booking/delete', ['bid' => $bid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button"><?= $this->t('Yes, delete') ?></a>
        </div>

        <div class="separator-small"></div>

        <div class="small-text gray"><?= $this->t('Remember that you can also set the booking status to disabled<br>without deleting it. This can be undone.') ?></div>
    </div>
</div>