<div class="bf-pricing">
    <div class="centered-text gray" style="margin: 8px 0px;">=</div>

    <div class="sandbox">
        <table class="default-table full-width">
            <tr>
                <td class="right-text gray">
                    <?= $this->t('Preliminary total price:') ?>
                </td>

                <td class="bf-pricing-price-col bordered-col">
                    <?= $this->priceFormat($this->priceTotal) ?>
                </td>
            </tr>
        </table>
    </div>
</div>