<?php

$this->setup(array(
    'title' => 'Delete bundle',
    'panel' => 'centered-panel large-sized',
    'tabs' => $this->backendDefaultTabs(),
    'back' => array(
        'Bundles' => $this->url('backend/bundle'),
    ),
));

$bid = $this->bundle->need('bid');

?>

<div>
    <h1><?= $this->t('Delete bundle') ?> <b><?= $this->bundle->getMeta('name') ?></b></h1>

    <div class="separator separator-line"></div>

    <div class="padded centered-text">
        <div><span class="symbolic symbolic-warning"><?= $this->t('Deleting this bundle cannot be undone. Are you sure?') ?></span></div>

        <div class="separator-small"></div>

        <div class="centered-text">
            <a href="<?= $this->url('backend/bundle') ?>" class="default-button"><?= $this->t('No, cancel') ?></a>
            <a href="<?= $this->url('backend/bundle/delete', ['bid' => $bid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button"><?= $this->t('Yes, delete') ?></a>
        </div>
    </div>
</div>