<?php

$this->setup(array(
    'title' => 'Users',
    'panel' => 'centered-panel large-sized',
    'tabs' => $this->backendDefaultTabs(),
    'back' => true,
));

?>

<div>
    <h1><?= $this->t('Users') ?></h1>

    <div class="separator-small"></div>

    <?= $this->backendInfo('user') ?>

    <div class="separator-small"></div>

    <?= $this->backendUsersFormat($this->users) ?>
</div>