<?php

$this->setup(array(
    'title' => 'Delete bill',
    'panel' => 'centered-panel large-sized',
    'tabs' => $this->backendDefaultTabs(),
    'back' => array(
        'Bills' => $this->url('backend/bill'),
    ),
));

$bid = $this->bill->need('bid');

?>

<div>
    <h1><?= $this->t('Delete bill') ?></h1>

    <div class="separator separator-line"></div>

    <div class="padded centered-text">
        <div><span class="symbolic symbolic-warning"><?= $this->t('Deleting this bill cannot be undone. Are you sure?') ?></span></div>

        <div class="separator-small"></div>

        <div class="centered-text">
            <a href="<?= $this->url('backend/bill') ?>" class="default-button"><?= $this->t('No, cancel') ?></a>
            <a href="<?= $this->url('backend/bill/delete', ['bid' => $bid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button"><?= $this->t('Yes, delete') ?></a>
        </div>
    </div>
</div>